version: "3.7"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
      - /app/.next
    depends_on:
      - backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - '1337:1337'
    volumes:
      - /app/node_modules
      - ./backend:/app
